create table public.notifications (
  notificationid bigint generated by default as identity not null,
  accountid text null,
  notification_data jsonb null,
  created_at timestamp with time zone not null default now(),
  notification_type public.notification_type null,
  read_at timestamp with time zone null,
  constraint notifications_pkey primary key (notificationid),
  constraint notifications_accountid_fkey foreign KEY (accountid) references accounts (accountid)
) TABLESPACE pg_default;

create trigger trg_notify_backend
after INSERT on notifications for EACH row
execute FUNCTION trgutil_notify_backend ();